### ISSUE TITLE
electron-rebuild fails after updating keytar to 7.7.0

### ISSUE THREAD

**Issue by Ranjith-Eswaran-G** [atom/node-keytar#431]
Node Version: 14.7.5
Electron version: 11.1.0

D:\build-error-fix\Application\app\node_modules\keytar\node
_modules\node-addon-api\napi-inl.h(1393,24): error C3861: 'napi_ob
ject_freeze': identifier not found [D:\build-error-fix\Application\app\node_modules\keytar\build\keytar.vcxproj]
D:\build-error-fix\Application\app\node_modules\keytar\node 
_modules\node-addon-api\napi-inl.h(1399,24): error C3861: 'napi_ob 
ject_seal': identifier not found [D:\build-error-fix\Cerebrata.Cer 
ulean\app\node_modules\keytar\build\keytar.vcxproj]
D:\build-error-fix\Application\app\node_modules\keytar\node 
_modules\node-addon-api\napi-inl.h(1606,24): error C3861: 'napi_is 
_detached_arraybuffer': identifier not found [D:\build-error-fix\Application\app\node_modules\keytar\build\keytar.vcxproj]    
D:\build-error-fix\Application\app\node_modules\keytar\node 
_modules\node-addon-api\napi-inl.h(1612,24): error C3861: 'napi_de 
tach_arraybuffer': identifier not found [D:\build-error-fix\Application\app\node_modules\keytar\build\keytar.vcxproj]
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'D:\build-error-fix\Application\app\node_modules\keytar'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1      

Error: node-gyp failed to rebuild 'D:\build-error-fix\Application\app\node_modules\keytar'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1      

    at ModuleRebuilder.rebuildNodeGypModule (D:\build-error-fix\Application\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Rebuilder.rebuildModuleAt (D:\build-error-fix\Application\node_modules\electron-rebuild\lib\src\rebuild.js:190:9) 
    at async Rebuilder.rebuild (D:\build-error-fix\Application\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)        
    at async D:\build-error-fix\Application\node_modules\electron-rebuild\lib\src\cli.js:146:9
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
